MANDT		MANDT		CLNT	3	0	Client
MAI_ALERT_GUID	AC_GUID		CHAR	32	0	Alert configuration: guid
MAI_OBJECT_NAME	CHAR256		CHAR	256	0	Data element for WWI callback
MAI_ALERT_TNAME	AC_NAME		CHAR	60	0	Alert configuration: MEA name
MAI_ALERT_NAME	AC_STRING	STRING	0	0	Alert configuration: string
MAI_TIMESTAMP	E2EA_TIMESTAMP	DEC	15	0	Time stamp
MAI_STATUS	E2EA_ALSTAT	CHAR	4	0	Alert status
SERVESS_NUMBER	CHAR10		CHAR	10	0	Character Field Length = 10
SERVESS_STATUS	CHAR3		CHAR	3	0	3-Byte field
UPDATE_DATE	DATS		DATS	8	0	Field of type DATS
UPDATE_TIME	UZEIT		TIMS	6	0	Time
