MANDT	MANDT	CLNT	3	0	Client
PARAM	CHAR20	CHAR	20	0	Char 20
VALUE	CHAR258	CHAR	258	0	Text for printing with WinWord

APP_LOG_OBJECT		    ZSERVESS
APP_LOG_SUBOBJECT	    ZALRTINTGR
IC_MON_ROUTE_RULE_ID	ZSERVESS_INT_RUL
RFC_DEST_PATH_PREFIX	/api/odata/businessobject/frs_evt_events
SERVESS_API_KEY		    DFA2A197453A4B998A282BE4160868B3
SERVESS_RFC_DEST	    ZSERVESS
TICKET_NAME_PREFIX	
ALERT_CONFIRM_TEXT	  Alert was confirmed from ServESS system
